### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by ericoc** [ericoc/seizures.ericoc.com#1]
Felt like documenting this because it was so strange.

I did `pip` upgrades per https://github.com/ericoc/seizures.ericoc.com/commit/8331ea6a5fb64cf4b399f1d749eda97679ddd0ef earlier. This began to cause the following error:

```
2023-05-03 20:25:33 EDT [ERROR] (70940): quote_from_bytes() expected bytes
Traceback (most recent call last):
  File "/Users/eric/code/seizures/__init__.py", line 158, in view_date
    return index(seizures=seizures, date=dt.isoformat())
  File "/Users/eric/code/seizures/__init__.py", line 176, in index
    return render_template(
  File "/Users/eric/code/seizures/venv/lib/python3.10/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/Users/eric/code/seizures/venv/lib/python3.10/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/Users/eric/code/seizures/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/eric/code/seizures/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/eric/code/seizures/templates/seizures.html.j2", line 65, in top-level template code
    {%- set date_url = url_for('view_date', when=seizure.local_time.strftime('%Y-%m-%d'), _anchor=seizure.unix_time) %}
  File "/Users/eric/code/seizures/venv/lib/python3.10/site-packages/flask/app.py", line 1700, in url_for
    _anchor = _url_quote(_anchor, safe="%!#$&'()*+,/:;=?@")
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/parse.py", line 869, in quote
    return quote_from_bytes(string, safe)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/parse.py", line 894, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

After originally thinking that this was due to my own use of `urllib` in the `parse_field` static method in `models.py`...

- [d3602aa77113f9a601f7c70807d2b91d62f4c84d](https://github.com/ericoc/seizures.ericoc.com/commit/d3602aa77113f9a601f7c70807d2b91d62f4c84d)
- [bea9a87ca8a906ffa4dee8f7fdf7c33ca7134309](https://github.com/ericoc/seizures.ericoc.com/commit/bea9a87ca8a906ffa4dee8f7fdf7c33ca7134309)
- [24fc23c638d8e1fb62e4deabde183f4f07e29eb9](https://github.com/ericoc/seizures.ericoc.com/commit/24fc23c638d8e1fb62e4deabde183f4f07e29eb9)
- [e208d9fc238e12e3c91fd2cdd1f21803c7a90fb9](https://github.com/ericoc/seizures.ericoc.com/commit/e208d9fc238e12e3c91fd2cdd1f21803c7a90fb9)

I actually paid more attention to the error and saw that it was about Jinja processing:

- [6137cdf538547b7e65ab942fb79b6c518092222d](https://github.com/ericoc/seizures.ericoc.com/commit/6137cdf538547b7e65ab942fb79b6c518092222d)

Problem solved! I was passing `unix_time` (an `int`) in the `url_for` `_anchor` field in two places, so making it a string resolved the `TypeError` being raised deeper in `urllib`... I am not sure if `Werkzeug` or `Flask` is where the actual change was? or if my SQLAlchemy changes earlier today (Wednesday, May 3, 2023) had anything to do with it (I don't think so)?

Anyways, thanks for reading!

**Comment by ericoc** [comment]
Resolved by https://github.com/ericoc/seizures.ericoc.com/commit/6137cdf538547b7e65ab942fb79b6c518092222d
